(ns set-game.subs
  (:require [re-frame.core :refer [reg-sub]]))

(def all-cards [[:diamond :green :1 :outlined]
                [:diamond :green :1 :solid]
                [:diamond :green :1 :stripped]
                [:diamond :green :2 :outline]
                [:diamond :green :2 :solid]
                [:diamond :green :2 :stripped]
                [:diamond :green :3 :outline]
                [:diamond :green :3 :solid]
                [:diamond :green :3 :stripped]
                [:diamond :purple :1 :outline]
                [:diamond :purple :1 :solid]
                [:diamond :purple :1 :stripped]
                [:diamond :purple :2 :outline]
                [:diamond :purple :2 :solid]
                [:diamond :purple :2 :stripped]
                [:diamond :purple :3 :outline]
                [:diamond :purple :3 :solid]
                [:diamond :purple :3 :stripped]
                [:diamond :red :1 :outline]
                [:diamond :red :1 :outlined]
                [:diamond :red :1 :solid]
                [:diamond :red :1 :stripped]
                [:diamond :red :2 :outline]
                [:diamond :red :2 :outlined]
                [:diamond :red :2 :solid]
                [:diamond :red :2 :stripped]
                [:diamond :red :3 :outline]
                [:diamond :red :3 :outlined]
                [:diamond :red :3 :solid]
                [:diamond :red :3 :stripped]
                [:oval :green :1 :outline]
                [:oval :green :1 :solid]
                [:oval :green :1 :stripped]
                [:oval :green :2 :outlined]
                [:oval :green :2 :solid]
                [:oval :green :2 :stripped]
                [:oval :green :3 :outlined]
                [:oval :green :3 :solid]
                [:oval :green :3 :stripped]
                [:oval :purple :1 :outlined]
                [:oval :purple :1 :solid]
                [:oval :purple :1 :stripped]
                [:oval :purple :2 :outlined]
                [:oval :purple :2 :solid]
                [:oval :purple :2 :stripped]
                [:oval :purple :3 :outlined]
                [:oval :purple :3 :solid]
                [:oval :purple :3 :stripped]
                [:oval :red :1 :outline]
                [:oval :red :1 :solid]
                [:oval :red :1 :stripped]
                [:oval :red :2 :outline]
                [:oval :red :2 :solid]
                [:oval :red :2 :stripped]
                [:oval :red :3 :outline]
                [:oval :red :3 :solid]
                [:oval :red :3 :stripped]
                [:squiggle :green :1 :outline]
                [:squiggle :green :1 :solid]
                [:squiggle :green :1 :stripped]
                [:squiggle :green :2 :outline]
                [:squiggle :green :2 :solid]
                [:squiggle :green :2 :stripped]
                [:squiggle :green :3 :outline]
                [:squiggle :green :3 :solid]
                [:squiggle :green :3 :stripped]
                [:squiggle :purple :1 :outline]
                [:squiggle :purple :1 :solid]
                [:squiggle :purple :1 :stripped]
                [:squiggle :purple :2 :outline]
                [:squiggle :purple :2 :solid]
                [:squiggle :purple :2 :stripped]
                [:squiggle :purple :3 :outline]
                [:squiggle :purple :3 :solid]
                [:squiggle :purple :3 :stripped]
                [:squiggle :red :1 :outline]
                [:squiggle :red :1 :solid]
                [:squiggle :red :1 :stripped]
                [:squiggle :red :2 :outline]
                [:squiggle :red :2 :solid]
                [:squiggle :red :2 :stripped]
                [:squiggle :red :3 :outline]
                [:squiggle :red :3 :solid]
                [:squiggle :red :3 :stripped]])
(reg-sub
  :get-board
  (fn [db _]
    (:board db)))

(reg-sub
  :get-greeting
  (fn [db _]
    (:greeting db)))